{
 "title": "WUD - What's up Docker",
 "description": "Dashboard for WUD (What's up Docker)",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Images to Update",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wud_containers{update_available=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Overview",
   "type": "table",
   "gridPos": { "h": 65, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by(image_registry_url, image_name, image_os, image_architecture, image_tag_value, result_tag, image_digest_watch, image_digest_repo, image_digest_value, update_available) (wud_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Update",
   "type": "timeseries",
   "gridPos": { "h": 27, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(sum by(image_registry_url, image_name, image_os, image_architecture, image_tag_value, result_tag) (wud_containers{update_available=\"true\"}))",
     "legendFormat": "Number of Images to update"
    }
   ]
  },
  {
   "title": "Images to Update",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 14, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(image_registry_url, image_name, image_os, image_architecture, image_tag_value, result_tag) (wud_containers{update_available=\"true\"})",
     "legendFormat": "{{image_name}}: {{image_tag_value}} -> {{result_tag}}"
    }
   ]
  }
 ]
}